name: NodeJS and MongoDB CI
on:
  delete:
    
defaults:
  run:
    working-directory: /TEAM-33H-backend
    
jobs:  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [3.6]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm install
      working-directory: ${{ env.working-directory }}
    - run: npm run lint
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - run: npm run test
      working-directory: ${{ env.working-directory }}
