name: NodeJS and MongoDB CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
    
defaults:
  run:
    working-directory: /TEAM-33H-backend
    
jobs:
  container-job:
    runs-on: ubuntu-latest
    
    # runs all of the steps inside the specified container rather than on the VM host.  
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:14.9.0-stretch

    services:
      mongodb:
        image: mongo
        # ports:
        # - 27017:27017
          
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Start MongoDB v3.6.8
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '3.6.8'
      env:
        # use mongodb for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        MONGODB_HOST: mongodb
        MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}     
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm install
      working-directory: ${{ env.working-directory }}
    - run: npm run lint
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - run: npm run test
      working-directory: ${{ env.working-directory }}
    - run: npm start
      working-directory: ${{ env.working-directory }}
